Repository KhronosGroup/OpenGL-Registry, pull requests merged in 2018-10, with the labels that each got.

#225 OVR_multiview/2 clarifications
  extensions/OVR/OVR_multiview.txt
  extensions/OVR/OVR_multiview2.txt
Labels: OpenGL, OpenGL ES

#224 add QCOM_YUV_texture_gather
  extensions/QCOM/QCOM_YUV_texture_gather.txt
  extensions/registry.py
  xml/gl.xml
Labels: OpenGL ES

#222 Define tokens for VIEW_CLASS_{EAC*,ETC2*,ASTC*}
  extensions/ARB/ARB_internalformat_query2.txt
  xml/gl.xml
Labels: OpenGL
